### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by jomo**
I know you have a build server already, but travis has fancy badges:
build:passing
[example build](https://travis-ci.org/RedstonerServer/Python-Plugin-Loader/builds/56232366)

### CODE REVIEW

**Comment by gdude2002** [comment]
I tend to not use travis because it doesn't produce artifacts, is inconsistent with build times and, well, I don't have access to the hardware.

Also, Bamboo has [this](http://bamboo.gserv.me/plugins/servlet/buildStatusImage/PLUG-PYPL) -

**Comment by jomo** [comment]
:+1:

**Comment by jomo** [comment]
@gdude2002 would you be ok with me merging this in now, since it's disabled [on bamboo](https://bamboo.gserv.me/browse/PLUG-PYPL)?
I'll manually add artifacts to GitHub releases. then.

**Comment by gdude2002** [comment]
Up to you, I didn't think anyone was still using this. I can enable it
again if needed.

**Comment by jomo** [comment]
Turns out I can't enable travis because this is a user repo.
Can you enable it [on Travis](https://travis-ci.org/profile/gdude2002) (and [on GitHub](https://github.com/gdude2002/Python-Plugin-Loader/settings/hooks) if that doesn't happen automagically)?

**Comment by gdude2002** [comment]
That should have done it.

**Pull request merged**
